# Generated by Django 5.2.7 on 2025-10-10 11:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(allow_unicode=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_own', models.BooleanField(default=False, verbose_name='is brand is for this company ?')),
                ('logo', models.ImageField(upload_to='product/brand/')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(allow_unicode=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.brandcountry', verbose_name='the country brand belongs to ')),
            ],
        ),
    ]
