# Generated by Django 5.2.7 on 2025-10-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandcountry',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
