# Generated by Django 5.2.7 on 2025-10-10 12:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_brand_slug_alter_brandcountry_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='product/country/')),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.country', verbose_name='the country brand belongs to '),
        ),
        migrations.DeleteModel(
            name='BrandCountry',
        ),
    ]
