# Generated by Django 5.2.7 on 2025-10-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_productcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default=None, upload_to='media/product/product-category/'),
            preserve_default=False,
        ),
    ]
