# Generated by Django 5.2.7 on 2025-11-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(max_length=256),
        ),
    ]
