# Generated by Django 5.2.7 on 2025-11-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
