# Generated by Django 5.2.7 on 2025-10-19 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.ImageField(upload_to='media/template/slider/slides')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='template.sliderconfig')),
            ],
        ),
        migrations.CreateModel(
            name='SlideBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image_url', models.ImageField(upload_to='media/template/slider/slide-box')),
                ('title', models.CharField(max_length=256)),
                ('link', models.URLField(default='/')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='template.sliderconfig')),
            ],
        ),
    ]
