# Generated by Django 5.2.7 on 2025-10-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidebox',
            name='link',
            field=models.CharField(default='/', max_length=256),
        ),
    ]
