# Generated by Django 5.2.7 on 2025-10-21 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_alter_slidebox_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('instagram_page', models.CharField(blank=True, max_length=128, null=True)),
                ('telegram_channel', models.CharField(blank=True, max_length=128, null=True)),
                ('whatsapp_support', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GrouLinkFooter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=128)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='template.footer')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=256)),
                ('group_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='template.groulinkfooter')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to='template/footer/license/')),
                ('url', models.CharField(max_length=256)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='template.footer')),
            ],
        ),
    ]
