# Generated by Django 5.2.7 on 2025-10-31 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='opt_code',
        ),
        migrations.AddField(
            model_name='user',
            name='opt_code_hashed',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
