# Generated by Django 5.2.7 on 2025-10-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_opt_code_user_opt_code_hashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='opt_code_hashed',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
