# Generated by Django 5.2.7 on 2025-11-01 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_opt_code_hashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.SlugField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
